branch-defaults:
  nfl-playoff-brackets:
    environment: mattwolfsonSite-env
environment-defaults:
  mattwolfsonSite-env:
    branch: null
    repository: null
global:
  application_name: mattwolfson-site
  default_ec2_keyname: matt-ec2
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Node.js running on
    64bit Amazon Linux/4.4.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
