/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './authentication.component';
import * as i1 from './auth.service';
import * as i2 from './authentication.component.ngfactory';
export function AuthenticationComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.AuthenticationComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.AuthService}}}],
      lifecycleHooks:([] as any[])},isComponent:true,selector:'app-authentication',
      exportAs:(null as any),inputs:{},outputs:{},hostListeners:{},hostProperties:{},
      hostAttributes:{},providers:([] as any[]),viewProviders:([] as any[]),queries:([] as any[]),
      viewQueries:([] as any[]),entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:2},componentViewType:i2.View_AuthenticationComponent_0,
      rendererType:i2.RenderType_AuthenticationComponent,componentFactory:i2.AuthenticationComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRG9jdW1lbnRzL0dpdGh1Yi9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9hdXRoL2F1dGhlbnRpY2F0aW9uLmNvbXBvbmVudC5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Eb2N1bWVudHMvR2l0aHViL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL2F1dGgvYXV0aGVudGljYXRpb24uY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
