/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './auth.module';
import * as i1 from './signup.component';
import * as i2 from './signup.component.ngfactory';
import * as i3 from './signin.component';
import * as i4 from './signin.component.ngfactory';
import * as i5 from './logout.component';
import * as i6 from './logout.component.ngfactory';
import * as i7 from '@angular/common';
import * as i8 from '@angular/core';
import * as i9 from '@angular/forms';
import * as i10 from '@angular/router';
import * as i11 from './signin.component.ngsummary';
import * as i12 from './signup.component.ngsummary';
import * as i13 from './logout.component.ngsummary';
import * as i14 from '../../../node_modules/@angular/common/common.ngsummary';
import * as i15 from '../../../node_modules/@angular/forms/forms.ngsummary';
import * as i16 from '../../../node_modules/@angular/router/router.ngsummary';
export function AuthModuleNgSummary():any[] {
  return [{summaryKind:2,type:{reference:i0.AuthModule,diDeps:([] as any[]),lifecycleHooks:([] as any[])},
      entryComponents:[{componentType:i1.SignupComponent,componentFactory:i2.SignupComponentNgFactory},
          {componentType:i3.SigninComponent,componentFactory:i4.SigninComponentNgFactory},
          {componentType:i5.LogoutComponent,componentFactory:i6.LogoutComponentNgFactory}],
      providers:[{provider:{token:{identifier:{reference:i7.NgLocalization}},useClass:{reference:i7.NgLocaleLocalization,
          diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i8.LOCALE_ID}}}],lifecycleHooks:([] as any[])},
          useValue:(undefined as any),useFactory:(null as any),useExisting:(undefined as any),
          deps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i8.LOCALE_ID}}}],multi:false},module:{reference:i7.CommonModule,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i9.FormBuilder,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])}},useClass:{reference:i9.FormBuilder,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])},useValue:(undefined as any),
          useFactory:(null as any),useExisting:(undefined as any),deps:([] as any[]),
          multi:false},module:{reference:i9.ReactiveFormsModule,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i9.ɵi,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])}},useClass:{reference:i9.ɵi,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])},useValue:(undefined as any),
          useFactory:(null as any),useExisting:(undefined as any),deps:([] as any[]),
          multi:false},module:{reference:i9.ReactiveFormsModule,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i10.ROUTES}},
          useClass:(null as any),useValue:[{path:'',redirectTo:'signup',pathMatch:'full'},
              {path:'signup',component:i1.SignupComponent},{path:'signin',component:i3.SigninComponent},
              {path:'logout',component:i5.LogoutComponent}],useFactory:(null as any),
          useExisting:(undefined as any),deps:(undefined as any),multi:true},module:{reference:i0.AuthModule,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])}}],modules:[{reference:i7.CommonModule,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])},{reference:i9.ɵba,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])},{reference:i9.ReactiveFormsModule,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])},{reference:i10.RouterModule,diDeps:[{isAttribute:false,
          isHost:false,isSelf:false,isSkipSelf:false,isOptional:true,token:{identifier:{reference:i10.ɵa}}},
          {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:true,
              token:{identifier:{reference:i10.Router}}}],lifecycleHooks:([] as any[])},
          {reference:i0.AuthModule,diDeps:([] as any[]),lifecycleHooks:([] as any[])}],
      exportedDirectives:([] as any[]),exportedPipes:([] as any[])},i11.SigninComponentNgSummary,
      i12.SignupComponentNgSummary,i13.LogoutComponentNgSummary,i14.CommonModuleNgSummary,
      i15.ɵbaNgSummary,i15.ReactiveFormsModuleNgSummary,i16.RouterModuleNgSummary];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRG9jdW1lbnRzL0dpdGh1Yi9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9hdXRoL2F1dGgubW9kdWxlLm5nc3VtbWFyeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0RvY3VtZW50cy9HaXRodWIvc2VlZC1wcm9qZWN0L2Fzc2V0cy9hcHAvYXV0aC9hdXRoLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
