/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './logout.component';
import * as i2 from './auth.service';
import * as i3 from '@angular/router';
const styles_LogoutComponent:any[] = ([] as any[]);
export const RenderType_LogoutComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_LogoutComponent,data:{}});
export function View_LogoutComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),4,'div',[['class','col-md-8 col-md-offset-2']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n			'])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),1,'button',[['class','btn btn-danger']],
          (null as any),[[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            var _co:i1.LogoutComponent = _v.component;
            if (('click' === en)) {
              const pd_0:any = ((<any>_co.onLogout()) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n				Logout\n			'])),
      (_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵted((null as any),['\n	']))],
      (null as any),(null as any));
}
export function View_LogoutComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-logout',([] as any[]),
      (null as any),(null as any),(null as any),View_LogoutComponent_0,RenderType_LogoutComponent)),
      i0.ɵdid(49152,(null as any),0,i1.LogoutComponent,[i2.AuthService,i3.Router],
          (null as any),(null as any))],(null as any),(null as any));
}
export const LogoutComponentNgFactory:i0.ComponentFactory<i1.LogoutComponent> = i0.ɵccf('app-logout',
    i1.LogoutComponent,View_LogoutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRG9jdW1lbnRzL0dpdGh1Yi9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9hdXRoL2xvZ291dC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovRG9jdW1lbnRzL0dpdGh1Yi9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9hdXRoL2xvZ291dC5jb21wb25lbnQudHMiLCJuZzovLy9EOi9Eb2N1bWVudHMvR2l0aHViL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL2F1dGgvbG9nb3V0LmNvbXBvbmVudC50cy5Mb2dvdXRDb21wb25lbnQuaHRtbCIsIm5nOi8vL0Q6L0RvY3VtZW50cy9HaXRodWIvc2VlZC1wcm9qZWN0L2Fzc2V0cy9hcHAvYXV0aC9sb2dvdXQuY29tcG9uZW50LnRzLkxvZ291dENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuXHRcdDxkaXYgY2xhc3M9XCJjb2wtbWQtOCBjb2wtbWQtb2Zmc2V0LTJcIj5cblx0XHRcdDxidXR0b24gY2xhc3M9XCJidG4gYnRuLWRhbmdlclwiIChjbGljayk9XCJvbkxvZ291dCgpXCI+XG5cdFx0XHRcdExvZ291dFxuXHRcdFx0PC9idXR0b24+XG5cdFx0PC9kaXY+XG5cdCIsIjxhcHAtbG9nb3V0PjwvYXBwLWxvZ291dD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLHlDQUNFO01BQUE7TUFBQSw0Q0FBc0M7TUFDckM7VUFBQTtZQUFBO1lBQUE7WUFBK0I7Y0FBQTtjQUFBO1lBQUE7WUFBL0I7VUFBQSxnQ0FBb0Q7TUFFM0MseUNBQ0o7Ozs7b0JDTFI7TUFBQTthQUFBO1VBQUE7OzsifQ==
