/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './logout.component';
import * as i1 from './auth.service';
import * as i2 from '@angular/router';
import * as i3 from './logout.component.ngfactory';
export function LogoutComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.LogoutComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.AuthService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.Router}}}],lifecycleHooks:([] as any[])},
      isComponent:true,selector:'app-logout',exportAs:(null as any),inputs:{},outputs:{},
      hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:2},componentViewType:i3.View_LogoutComponent_0,
      rendererType:i3.RenderType_LogoutComponent,componentFactory:i3.LogoutComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRG9jdW1lbnRzL0dpdGh1Yi9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9hdXRoL2xvZ291dC5jb21wb25lbnQubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovRG9jdW1lbnRzL0dpdGh1Yi9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9hdXRoL2xvZ291dC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
