/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '@angular/common';
import * as i3 from './header.component';
const styles_HeaderComponent:any[] = ([] as any[]);
export const RenderType_HeaderComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_HeaderComponent,data:{}});
export function View_HeaderComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),25,'header',[['class','row']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['	\n			'])),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),22,'nav',[['class','col-md-8 col-md-offset-2']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['	\n				'])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),19,'ul',[['class','nav nav-pills']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['	\n					'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),7,'li',[['routerLinkActive',
          'active']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(1720320,(null as any),2,i1.RouterLinkActive,[i1.Router,i0.ElementRef,
          i0.Renderer2,i0.ChangeDetectorRef],{routerLinkActive:[0,'routerLinkActive']},
          (null as any)),i0.ɵqud(603979776,1,{links:1}),i0.ɵqud(603979776,2,{linksWithHrefs:1}),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),3,'a',([] as any[]),[[1,'target',
          0],[8,'href',4]],[[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        if (('click' === en)) {
          const pd_0:any = ((<any>i0.ɵnov(_v,12).onClick($event.button,$event.ctrlKey,
              $event.metaKey,$event.shiftKey)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),i0.ɵdid(671744,[[2,4]],0,i1.RouterLinkWithHref,
          [i1.Router,i1.ActivatedRoute,i2.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),i0.ɵpad(1),(_l()(),i0.ɵted((null as any),['Auth'])),(_l()(),
          i0.ɵted((null as any),['\n					'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          7,'li',[['routerLinkActive','active']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),i0.ɵdid(1720320,(null as any),2,i1.RouterLinkActive,
          [i1.Router,i0.ElementRef,i0.Renderer2,i0.ChangeDetectorRef],{routerLinkActive:[0,
              'routerLinkActive']},(null as any)),i0.ɵqud(603979776,3,{links:1}),i0.ɵqud(603979776,
          4,{linksWithHrefs:1}),(_l()(),i0.ɵeld(0,(null as any),(null as any),3,'a',
          ([] as any[]),[[1,'target',0],[8,'href',4]],[[(null as any),'click']],(_v,
              en,$event) => {
            var ad:boolean = true;
            if (('click' === en)) {
              const pd_0:any = ((<any>i0.ɵnov(_v,21).onClick($event.button,$event.ctrlKey,
                  $event.metaKey,$event.shiftKey)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),i0.ɵdid(671744,[[4,4]],0,i1.RouterLinkWithHref,
          [i1.Router,i1.ActivatedRoute,i2.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),i0.ɵpad(1),(_l()(),i0.ɵted((null as any),['Messaging'])),
      (_l()(),i0.ɵted((null as any),['	\n				'])),(_l()(),i0.ɵted((null as any),['\n			'])),
      (_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵted((null as any),['\n	']))],
      (_ck,_v) => {
        const currVal_0:any = 'active';
        _ck(_v,8,0,currVal_0);
        const currVal_3:any = _ck(_v,13,0,'/auth');
        _ck(_v,12,0,currVal_3);
        const currVal_4:any = 'active';
        _ck(_v,17,0,currVal_4);
        const currVal_7:any = _ck(_v,22,0,'/messages');
        _ck(_v,21,0,currVal_7);
      },(_ck,_v) => {
        const currVal_1:any = i0.ɵnov(_v,12).target;
        const currVal_2:any = i0.ɵnov(_v,12).href;
        _ck(_v,11,0,currVal_1,currVal_2);
        const currVal_5:any = i0.ɵnov(_v,21).target;
        const currVal_6:any = i0.ɵnov(_v,21).href;
        _ck(_v,20,0,currVal_5,currVal_6);
      });
}
export function View_HeaderComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-header',([] as any[]),
      (null as any),(null as any),(null as any),View_HeaderComponent_0,RenderType_HeaderComponent)),
      i0.ɵdid(49152,(null as any),0,i3.HeaderComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const HeaderComponentNgFactory:i0.ComponentFactory<i3.HeaderComponent> = i0.ɵccf('app-header',
    i3.HeaderComponent,View_HeaderComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRG9jdW1lbnRzL0dpdGh1Yi9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9oZWFkZXIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0RvY3VtZW50cy9HaXRodWIvc2VlZC1wcm9qZWN0L2Fzc2V0cy9hcHAvaGVhZGVyLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L0RvY3VtZW50cy9HaXRodWIvc2VlZC1wcm9qZWN0L2Fzc2V0cy9hcHAvaGVhZGVyLmNvbXBvbmVudC50cy5IZWFkZXJDb21wb25lbnQuaHRtbCIsIm5nOi8vL0Q6L0RvY3VtZW50cy9HaXRodWIvc2VlZC1wcm9qZWN0L2Fzc2V0cy9hcHAvaGVhZGVyLmNvbXBvbmVudC50cy5IZWFkZXJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcblx0XHQ8aGVhZGVyIGNsYXNzPVwicm93XCI+XHRcblx0XHRcdDxuYXYgY2xhc3M9XCJjb2wtbWQtOCBjb2wtbWQtb2Zmc2V0LTJcIj5cdFxuXHRcdFx0XHQ8dWwgY2xhc3M9XCJuYXYgbmF2LXBpbGxzXCI+XHRcblx0XHRcdFx0XHQ8bGkgcm91dGVyTGlua0FjdGl2ZT1cImFjdGl2ZVwiPjxhIFtyb3V0ZXJMaW5rXT1cIlsnL2F1dGgnXVwiPkF1dGg8L2E+PC9saT5cblx0XHRcdFx0XHQ8bGkgcm91dGVyTGlua0FjdGl2ZT1cImFjdGl2ZVwiPjxhICBbcm91dGVyTGlua109XCJbJy9tZXNzYWdlcyddXCI+TWVzc2FnaW5nPC9hPjwvbGk+XHRcblx0XHRcdFx0PC91bD5cblx0XHRcdDwvbmF2PlxuXHRcdDwvaGVhZGVyPlxuXHQiLCI8YXBwLWhlYWRlcj48L2FwcC1oZWFkZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQSx5Q0FDRTtNQUFBO01BQUEsOEJBQW9CLDJDQUNuQjthQUFBO1VBQUE7TUFBc0MsNENBQ3JDO1VBQUE7VUFBQSw0Q0FBMEI7VUFBQSxlQUN6QjtVQUFBO2FBQUE7MkNBQUE7VUFBQTtNQUE4QjtVQUFBO1FBQUE7UUFBQTtVQUFBO2NBQUE7VUFBQTtRQUFBO1FBQUE7TUFBQSx1Q0FBQTtVQUFBO1VBQUEsc0JBQUcsSUFBeUIseUNBQWE7aUJBQUEsNkJBQ3ZFO1VBQUE7VUFBQSxxQ0FBQTtVQUFBO2NBQUE7VUFBQSxzQkFBOEI7VUFBQTt1QkFBQTtZQUFBO1lBQUE7Y0FBQTtrQkFBQTtjQUFBO1lBQUE7WUFBQTtVQUFBLHVDQUFBO1VBQUE7VUFBQSxzQkFBSSxJQUE2QjtNQUFrQiw0Q0FDN0U7TUFDQSx5Q0FDRTs7UUFKRjtRQUFKLFdBQUksU0FBSjtRQUFpQztRQUFILFlBQUcsU0FBSDtRQUMxQjtRQUFKLFlBQUksU0FBSjtRQUFrQztRQUFKLFlBQUksU0FBSjs7UUFEQTtRQUFBO1FBQUEsWUFBQSxtQkFBQTtRQUNBO1FBQUE7UUFBQSxZQUFBLG1CQUFBOzs7O29CQ0xuQztNQUFBO2FBQUE7VUFBQTs7OyJ9
