/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './message.component.ngfactory';
import * as i2 from './message.component';
import * as i3 from './message.service';
import * as i4 from '@angular/common';
import * as i5 from './message-lister.component';
const styles_MessageListerComponent:any[] = ([] as any[]);
export const RenderType_MessageListerComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_MessageListerComponent,data:{}});
function View_MessageListerComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-message',
      ([] as any[]),(null as any),(null as any),(null as any),i1.View_MessageComponent_0,
      i1.RenderType_MessageComponent)),i0.ɵdid(49152,(null as any),0,i2.MessageComponent,
      [i3.MessageService],{message:[0,'message']},(null as any))],(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_MessageListerComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),4,'div',[['class','col-md-8 col-md-offset-2']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n			'])),
      (_l()(),i0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_MessageListerComponent_1)),
      i0.ɵdid(802816,(null as any),0,i4.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,
          i0.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n		'])),(_l()(),i0.ɵted((null as any),['\n	']))],(_ck,_v) => {
    var _co:i5.MessageListerComponent = _v.component;
    const currVal_0:any = _co.messages;
    _ck(_v,4,0,currVal_0);
  },(null as any));
}
export function View_MessageListerComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-message-list',
      ([] as any[]),(null as any),(null as any),(null as any),View_MessageListerComponent_0,
      RenderType_MessageListerComponent)),i0.ɵdid(114688,(null as any),0,i5.MessageListerComponent,
      [i3.MessageService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const MessageListerComponentNgFactory:i0.ComponentFactory<i5.MessageListerComponent> = i0.ɵccf('app-message-list',
    i5.MessageListerComponent,View_MessageListerComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRG9jdW1lbnRzL0dpdGh1Yi9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlLWxpc3Rlci5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovRG9jdW1lbnRzL0dpdGh1Yi9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlLWxpc3Rlci5jb21wb25lbnQudHMiLCJuZzovLy9EOi9Eb2N1bWVudHMvR2l0aHViL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2UtbGlzdGVyLmNvbXBvbmVudC50cy5NZXNzYWdlTGlzdGVyQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9EOi9Eb2N1bWVudHMvR2l0aHViL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2UtbGlzdGVyLmNvbXBvbmVudC50cy5NZXNzYWdlTGlzdGVyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG5cdFx0PGRpdiBjbGFzcz1cImNvbC1tZC04IGNvbC1tZC1vZmZzZXQtMlwiPlxuXHRcdFx0PGFwcC1tZXNzYWdlIFxuXHRcdFx0XHRbbWVzc2FnZV09XCJtZXNzYWdlXCIgXG5cdFx0XHRcdCpuZ0Zvcj1cImxldCBtZXNzYWdlIG9mIG1lc3NhZ2VzXCI+PC9hcHAtbWVzc2FnZT5cblx0XHQ8L2Rpdj5cblx0IiwiPGFwcC1tZXNzYWdlLWxpc3Q+PC9hcHAtbWVzc2FnZS1saXN0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNFRztNQUFBO29DQUFBLFVBQUE7TUFBQTtJQUNDO0lBREQsV0FDQyxTQUREOzs7O29CQUZILHlDQUNFO01BQUE7TUFBQSw0Q0FBc0M7TUFDckM7YUFBQTs0QkFBQSx5Q0FFZ0Q7VUFBQSxXQUMzQzs7SUFESjtJQUZELFdBRUMsU0FGRDs7OztvQkNGSDtNQUFBO3VDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
