/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './message-input.component.ngfactory';
import * as i2 from './message-input.component';
import * as i3 from './message.service';
import * as i4 from './message-lister.component.ngfactory';
import * as i5 from './message-lister.component';
import * as i6 from './messages.component';
const styles_MessagesComponent:any[] = ([] as any[]);
export const RenderType_MessagesComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_MessagesComponent,data:{}});
export function View_MessagesComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),4,'div',[['class','row']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n			'])),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),1,'app-message-input',([] as any[]),(null as any),
          (null as any),(null as any),i1.View_MessageInputComponent_0,i1.RenderType_MessageInputComponent)),
      i0.ɵdid(114688,(null as any),0,i2.MessageInputComponent,[i3.MessageService],
          (null as any),(null as any)),(_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),
          i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          0,'hr',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),4,'div',[['class','row']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n			'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-message-list',
          ([] as any[]),(null as any),(null as any),(null as any),i4.View_MessageListerComponent_0,
          i4.RenderType_MessageListerComponent)),i0.ɵdid(114688,(null as any),0,i5.MessageListerComponent,
          [i3.MessageService],(null as any),(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n		'])),(_l()(),i0.ɵted((null as any),['\n	']))],(_ck,_v) => {
    _ck(_v,4,0);
    _ck(_v,12,0);
  },(null as any));
}
export function View_MessagesComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-messages',
      ([] as any[]),(null as any),(null as any),(null as any),View_MessagesComponent_0,
      RenderType_MessagesComponent)),i0.ɵdid(49152,(null as any),0,i6.MessagesComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const MessagesComponentNgFactory:i0.ComponentFactory<i6.MessagesComponent> = i0.ɵccf('app-messages',
    i6.MessagesComponent,View_MessagesComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRG9jdW1lbnRzL0dpdGh1Yi9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlcy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovRG9jdW1lbnRzL0dpdGh1Yi9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlcy5jb21wb25lbnQudHMiLCJuZzovLy9EOi9Eb2N1bWVudHMvR2l0aHViL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC50cy5NZXNzYWdlc0NvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovRG9jdW1lbnRzL0dpdGh1Yi9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlcy5jb21wb25lbnQudHMuTWVzc2FnZXNDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcblx0XHQ8ZGl2IGNsYXNzPVwicm93XCI+XG5cdFx0XHQ8YXBwLW1lc3NhZ2UtaW5wdXQ+PC9hcHAtbWVzc2FnZS1pbnB1dD5cblx0XHQ8L2Rpdj5cblx0XHQ8aHI+XG5cdFx0PGRpdiBjbGFzcz1cInJvd1wiPlxuXHRcdFx0PGFwcC1tZXNzYWdlLWxpc3Q+PC9hcHAtbWVzc2FnZS1saXN0PlxuXHRcdDwvZGl2PlxuXHQiLCI8YXBwLW1lc3NhZ2VzPjwvYXBwLW1lc3NhZ2VzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUEseUNBQ0U7TUFBQTtNQUFBLDhCQUFpQiwwQ0FDaEI7YUFBQTtVQUFBO2FBQUE7VUFBQSw2QkFBdUMseUNBQ2xDO2lCQUFBLDBCQUNOO1VBQUE7VUFBQSxnQkFBSSx5Q0FDSjtVQUFBO1VBQUEsNENBQWlCO1VBQUEsWUFDaEI7VUFBQTs4Q0FBQSxVQUFBO1VBQUEsaURBQXFDO1VBQUEsV0FDaEM7SUFMTDtJQUlBOzs7O29CQ05IO01BQUE7a0NBQUEsVUFBQTtNQUFBOzs7In0=
