/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './message.component';
import * as i3 from './message.service';
const styles_MessageComponent:any[] = ['.author[_ngcontent-%COMP%] {\n			display: inline-block;\n			font-style: italic;\n			font-size: 12px;\n			width: 80%;\n		}\n		.config[_ngcontent-%COMP%] {\n			display: inline-block;\n			text-align: right;\n			font-size: 12px;\n			width: 19%;\n		}'];
export const RenderType_MessageComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_MessageComponent,data:{}});
function View_MessageComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),7,'div',[['class',
      'config']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n			'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'a',([] as any[]),(null as any),[[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            var _co:any = _v.component;
            if (('click' === en)) {
              const pd_0:any = ((<any>_co.onEdit()) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Edit'])),
      (_l()(),i0.ɵted((null as any),['\n			'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'a',([] as any[]),(null as any),[[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            var _co:any = _v.component;
            if (('click' === en)) {
              const pd_0:any = ((<any>_co.onDelete()) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Delete'])),
      (_l()(),i0.ɵted((null as any),['\n		']))],(null as any),(null as any));
}
export function View_MessageComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),13,'article',[['class',
      'panel panel-default']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted((null as any),['\n	'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'div',[['class','panel-body']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n		','\n	'])),
      (_l()(),i0.ɵted((null as any),['\n	'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          7,'footer',[['class','panel-footer']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),
          i0.ɵeld(0,(null as any),(null as any),1,'div',[['class','author']],(null as any),
              (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n			','\n		'])),(_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵand(16777216,
          (null as any),(null as any),1,(null as any),View_MessageComponent_1)),i0.ɵdid(16384,
          (null as any),0,i1.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,'ngIf']},
          (null as any)),(_l()(),i0.ɵted((null as any),['\n	'])),(_l()(),i0.ɵted((null as any),
          ['\n']))],(_ck,_v) => {
    var _co:i2.MessageComponent = _v.component;
    const currVal_2:any = _co.belongsToUser();
    _ck(_v,11,0,currVal_2);
  },(_ck,_v) => {
    var _co:i2.MessageComponent = _v.component;
    const currVal_0:any = _co.message.content;
    _ck(_v,3,0,currVal_0);
    const currVal_1:any = _co.message.username;
    _ck(_v,8,0,currVal_1);
  });
}
export function View_MessageComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-message',
      ([] as any[]),(null as any),(null as any),(null as any),View_MessageComponent_0,
      RenderType_MessageComponent)),i0.ɵdid(49152,(null as any),0,i2.MessageComponent,
      [i3.MessageService],(null as any),(null as any))],(null as any),(null as any));
}
export const MessageComponentNgFactory:i0.ComponentFactory<i2.MessageComponent> = i0.ɵccf('app-message',
    i2.MessageComponent,View_MessageComponent_Host_0,{message:'message'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRG9jdW1lbnRzL0dpdGh1Yi9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Eb2N1bWVudHMvR2l0aHViL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2UuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovRG9jdW1lbnRzL0dpdGh1Yi9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovRG9jdW1lbnRzL0dpdGh1Yi9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlLmNvbXBvbmVudC50cy5NZXNzYWdlQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGFydGljbGUgY2xhc3M9XCJwYW5lbCBwYW5lbC1kZWZhdWx0XCI+XHJcblx0PGRpdiBjbGFzcz1cInBhbmVsLWJvZHlcIj5cclxuXHRcdHt7bWVzc2FnZS5jb250ZW50fX1cclxuXHQ8L2Rpdj5cclxuXHQ8Zm9vdGVyIGNsYXNzPVwicGFuZWwtZm9vdGVyXCI+XHJcblx0XHQ8ZGl2IGNsYXNzPVwiYXV0aG9yXCI+XHJcblx0XHRcdHt7bWVzc2FnZS51c2VybmFtZX19XHJcblx0XHQ8L2Rpdj5cclxuXHRcdDxkaXYgY2xhc3M9XCJjb25maWdcIiAqbmdJZj1cImJlbG9uZ3NUb1VzZXIoKVwiPlxyXG5cdFx0XHQ8YSAoY2xpY2spPVwib25FZGl0KClcIj5FZGl0PC9hPlxyXG5cdFx0XHQ8YSAoY2xpY2spPVwib25EZWxldGUoKVwiPkRlbGV0ZTwvYT5cclxuXHRcdDwvZGl2PlxyXG5cdDwvZm9vdGVyPlxyXG48L2FydGljbGU+IiwiPGFwcC1tZXNzYWdlPjwvYXBwLW1lc3NhZ2U+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OztvQkNRRTtNQUFBO01BQTRDLDBDQUMzQztVQUFBO1lBQUE7WUFBQTtZQUFHO2NBQUE7Y0FBQTtZQUFBO1lBQUg7VUFBQSxnQ0FBc0I7TUFBUSwwQ0FDOUI7VUFBQTtZQUFBO1lBQUE7WUFBRztjQUFBO2NBQUE7WUFBQTtZQUFIO1VBQUEsZ0NBQXdCO01BQVU7OztvQkFWckM7TUFBQTtNQUFBLGdCQUFxQyx3Q0FDcEM7TUFBQTtNQUFBLDhCQUF3QjtNQUVsQix3Q0FDTjtVQUFBO1VBQUEsOEJBQTZCLHlDQUM1QjtpQkFBQTtjQUFBLDBEQUFvQjtVQUFBLG1CQUVkLHlDQUNOO1VBQUEsNkVBQUE7VUFBQTtVQUFBLGVBR00sd0NBQ0U7VUFBQTs7SUFKWTtJQUFwQixZQUFvQixTQUFwQjs7O0lBUHVCO0lBQUE7SUFJSDtJQUFBOzs7O29CQ0x0QjtNQUFBO2lDQUFBLFVBQUE7TUFBQTs7OyJ9
