/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './message.module';
import * as i1 from '@angular/common';
import * as i2 from '@angular/core';
import * as i3 from '@angular/forms';
import * as i4 from './message.service';
import * as i5 from '@angular/http';
import * as i6 from '../errors/error.service';
import * as i7 from './messages.component.ngsummary';
import * as i8 from './message-lister.component.ngsummary';
import * as i9 from './message.component.ngsummary';
import * as i10 from './message-input.component.ngsummary';
import * as i11 from '../../../node_modules/@angular/common/common.ngsummary';
import * as i12 from '../../../node_modules/@angular/forms/forms.ngsummary';
export function MessageModuleNgSummary():any[] {
  return [{summaryKind:2,type:{reference:i0.MessageModule,diDeps:([] as any[]),lifecycleHooks:([] as any[])},
      entryComponents:([] as any[]),providers:[{provider:{token:{identifier:{reference:i1.NgLocalization}},
          useClass:{reference:i1.NgLocaleLocalization,diDeps:[{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i2.LOCALE_ID}}}],
              lifecycleHooks:([] as any[])},useValue:(undefined as any),useFactory:(null as any),
          useExisting:(undefined as any),deps:[{isAttribute:false,isHost:false,isSelf:false,
              isSkipSelf:false,isOptional:false,token:{identifier:{reference:i2.LOCALE_ID}}}],
          multi:false},module:{reference:i1.CommonModule,diDeps:([] as any[]),lifecycleHooks:([] as any[])}},
          {provider:{token:{identifier:{reference:i3.ɵi,diDeps:([] as any[]),lifecycleHooks:([] as any[])}},
              useClass:{reference:i3.ɵi,diDeps:([] as any[]),lifecycleHooks:([] as any[])},
              useValue:(undefined as any),useFactory:(null as any),useExisting:(undefined as any),
              deps:([] as any[]),multi:false},module:{reference:i3.FormsModule,diDeps:([] as any[]),
              lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i4.MessageService,
              diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,
                  isOptional:false,token:{identifier:{reference:i5.Http}}},{isAttribute:false,
                  isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i6.ErrorService}}}],
              lifecycleHooks:([] as any[])}},useClass:{reference:i4.MessageService,
              diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,
                  isOptional:false,token:{identifier:{reference:i5.Http}}},{isAttribute:false,
                  isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i6.ErrorService}}}],
              lifecycleHooks:([] as any[])},useValue:(undefined as any),useFactory:(null as any),
              useExisting:(undefined as any),deps:[{isAttribute:false,isHost:false,
                  isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.Http}}},
                  {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                      token:{identifier:{reference:i6.ErrorService}}}],multi:false},
              module:{reference:i0.MessageModule,diDeps:([] as any[]),lifecycleHooks:([] as any[])}}],
      modules:[{reference:i1.CommonModule,diDeps:([] as any[]),lifecycleHooks:([] as any[])},
          {reference:i3.ɵba,diDeps:([] as any[]),lifecycleHooks:([] as any[])},{reference:i3.FormsModule,
              diDeps:([] as any[]),lifecycleHooks:([] as any[])},{reference:i0.MessageModule,
              diDeps:([] as any[]),lifecycleHooks:([] as any[])}],exportedDirectives:([] as any[]),
      exportedPipes:([] as any[])},i7.MessagesComponentNgSummary,i8.MessageListerComponentNgSummary,
      i9.MessageComponentNgSummary,i10.MessageInputComponentNgSummary,i11.CommonModuleNgSummary,
      i12.ɵbaNgSummary,i12.FormsModuleNgSummary,{summaryKind:3,type:{reference:i4.MessageService,
          diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i5.Http}}},{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i6.ErrorService}}}],
          lifecycleHooks:([] as any[])}}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRG9jdW1lbnRzL0dpdGh1Yi9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlLm1vZHVsZS5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Eb2N1bWVudHMvR2l0aHViL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2UubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
